### ISSUE TITLE
Prometheus timeouts

### ISSUE THREAD

**Issue by eirc** [kiwigrid/k8s-sidecar#23]
In our setup prometheus takes a few minutes to load up and be able to respond to requests. This also apparently produces a `ReadTimeoutError` which is not handled by the current [retry configuration](/kiwigrid/k8s-sidecar/blob/master/sidecar/sidecar.py#L26).

So two things proposed here:
1. Add read parameter to enable retries on read errors ([related docs](https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#module-urllib3.util.retry)).
2. Increase max number of retries to 10 or more so it can retry for a few minutes.

I didn't send a PR since I'd prefer discussing the numbers first. I can send one as soon as there's an agreement.

EDIT: I guess prometheus is unrelated to this project so I shouldn't really mention it anyway. Also maybe these numbers could be exported as configurable values?

**Comment by Tim-Smyth** [comment]
Hi @eirc,
Thanks for our input. What would you say about making the whole retry config override-able? We could add the retry limit for read operations but if would still fail your usecase due to the total limit. So I think it would be handy to make both configurable. What would you think about that?

**Comment by eirc** [comment]
Hey @Tim-Smyth that's pretty much what I did in #24 I think.
