### ISSUE TITLE
Compatibility with K8s v1.25

### ISSUE THREAD

**Issue by padmeshgit** [kiwigrid/k8s-sidecar#247]
Are this version v1.19.5 and all future versions compatible with K8s version v1.25? Please suggest

**Comment by jekkel** [comment]
Each PR gets tested against multiple k8s versions. v1.19.5 has been tested against:

![image](https://user-images.githubusercontent.com/701091/212061921-bdf9b2b4-3b55-463e-ab78-eb56c20ba20c.png)

Currently we're testing each PR against:

![image](https://user-images.githubusercontent.com/701091/212062029-4a7344c2-b6a9-4077-956e-016d776cec97.png)

The source of this can be found in the [build and test action](https://github.com/kiwigrid/k8s-sidecar/blob/master/.github/workflows/build_and_test.yaml#L34-L51).

**Comment by padmeshgit** [comment]
Thanks for the quick response, Appreciate it.

**Comment by jekkel** [comment]
You're welcome.

**Comment by reddy2018** [comment]
have you test it for k0s 1.28. since i am getting an error

Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    14m                   default-scheduler  Successfully assigned monitoring/kube-prometheus-stack-grafana-76b89b8446-b2flk to ip-10-0-0-180.us-east-2.compute.internal
  Warning  FailedMount  14m                   kubelet            MountVolume.SetUp failed for volume "kube-api-access-5mmst" : failed to sync configmap cache: timed out waiting for the condition
  Normal   Pulling      14m                   kubelet            Pulling image "docker.io/grafana/grafana:10.2.2"
  Normal   Created      14m                   kubelet            Created container grafana
  Normal   Pulled       14m                   kubelet            Successfully pulled image "docker.io/grafana/grafana:10.2.2" in 14.303s (14.303s including waiting)
  Warning  Failed       14m (x2 over 14m)     kubelet            Failed to pull image "quay.io/quay.io/kiwigrid/k8s-sidecar:1.25.2": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/quay.io/kiwigrid/k8s-sidecar:1.25.2": failed to resolve reference "quay.io/quay.io/kiwigrid/k8s-sidecar:1.25.2": quay.io/quay.io/kiwigrid/k8s-sidecar:1.25.2: not found
  Warning  Failed       14m (x2 over 14m)     kubelet            Error: ErrImagePull
  Normal   Pulling      14m (x2 over 14m)     kubelet            Pulling image "quay.io/quay.io/kiwigrid/k8s-sidecar:1.25.2"
  Normal   Started      14m                   kubelet            Started container grafana
  Warning  Failed       14m (x3 over 14m)     kubelet            Error: ImagePullBackOff
  Normal   BackOff      14m (x3 over 14m)     kubelet            Back-off pulling image "quay.io/quay.io/kiwigrid/k8s-sidecar:1.25.2"
  Warning  Failed       14m                   kubelet            Error: ImagePullBackOff
  Warning  Unhealthy    13m (x5 over 14m)     kubelet            Readiness probe failed: Get "http://10.0.0.181:3000/api/health": dial tcp 10.0.0.181:3000: connect: connection refused
  Normal   BackOff      4m27s (x44 over 14m)  kubelet            Back-off pulling image "quay.io/quay.io/kiwigrid/k8s-sidecar:1.25.2"

**Comment by reddy2018** [comment]
i am using the prometheus_chart_version    = "55.4.0" and eks_version     = "1.28"
