### ISSUE TITLE
Log python exceptions in json format

### ISSUE THREAD

**Issue by jkroepke** [kiwigrid/k8s-sidecar#331]
k8s-sidecare supports json logging, however for any python related exception, the standard format appears on stdout. This is really hard, because on loki, each single line is a dedicated message.

It would be great, if exceptions could be caught in general and can be logging by the configured logging handler

**Comment by ChristianGeie** [comment]
JSON logging is also on our bucket list. We wanted to implement this so that you can switch between plain and JSON logging via feature toggle. On the other hand, in a k8s environment we could also do JSON logging exclusively.

Do you already have an approach or a PR draft that implements the JSON logging feature?

**Comment by jkroepke** [comment]
Currently, JSON logging is implement, only exception are raises on stdout, as-is.

**Comment by ChristianGeie** [comment]
done
see https://github.com/kiwigrid/k8s-sidecar/pull/333
