### ISSUE TITLE
Configmaps containing files deployed to many namespaces causes premature delete

### ISSUE THREAD

**Issue by GregHamilton007** [kiwigrid/k8s-sidecar#44]
We are installing a configmap (containing a label that the sidecar picks up) to 2 different namespaces (namespaceA and namespaceB). WHEN the configmap is installed to namespaceA, the file in the configmap is added correctly to the specified directory. When the configmap is installed to namespaceB, the sidecar detects that the dashboard contained in the configmap is already discovered and is not added a second time... ALL is good until this point. When namespaceB is wiped of all of its resources the sidecar detects that the configmap is deleted, the file is deleted and is no longer available to namespaceA, despite the namespace persisting and containing the configmap.

The sidecar doesn't keep track that multiple deployments contain the configmap. Hence application that use the file contained in the configmap installed in namespace A are failing.

This issue has been discovered since we are installing a helm chart containing the configmap to a namespace that persists and to another namespace that is just present while tests are being run against it.

**What you expected to happen:**

The sidecar would detect and keep track of which releases contain configmaps which use the file, and only remove the file when all releases using that file are deleted

**How to reproduce it (as minimally and precisely as possible):**

1. Install configmap describing file, with label detectable by the sidecar twice (two seperate releases)
2. Delete one of the releases
3. Check specified directory where files in configmap resources are to be written to.

**Potential Fix**

Store a map of {metadata.namespace}/{metadata.name} to file for each resource with the specified label, and only run delete if ALL entries mapped to that file are deleted

https://github.com/kiwigrid/k8s-sidecar/blob/dd39aec87748c5e62a20d51f831658af96e94f37/sidecar/resources.py#L110-L114

**Comment by jekkel** [comment]
I consider this a very edge case because in general the two config maps are different and even the data of the duplicated config map key is very likely to be different. Assuming this, which configmap should be prioritized higher? How to deterministically choose the file content? For avoiding such kind of conflicts the `UNIQUE_FILENAMES` environment variable has been introduced which prefixes the key with configmap/secret name name and k8s namespace. 

In your use case this means 2 different files would be created and removed individually. Would this solve your issue?
